INFERENCE:
  # CHANGE TO YOUR PATHS
  IMAGE_NAME: /home/meganng/scratch/Data/TestData.tif
  OUTPUT_PATH: /home/meganng/scratch/ModelOutputs/Predictions
  OUTPUT_NAME: TestData_predictions.tif

  IS_ABSOLUTE_PATH: True
  INPUT_SIZE: [16, 256, 256]
  OUTPUT_SIZE: [16, 256, 256]
  OUTPUT_ACT: ["sigmoid"]
  
  PAD_SIZE: [8, 28, 28]
  AUG_MODE: mean
  AUG_NUM: 16
  STRIDE: [8,128,128]
  SAMPLES_PER_BATCH: 8
