SYSTEM:
  NUM_GPUS: 2
  NUM_CPUS: 16
AUGMENTOR:
  SMOOTH: False
MODEL:
  ARCHITECTURE: unet_plus_3d # unet_3d
  BLOCK_TYPE: residual_se
  ACT_MODE: leaky_relu
  INPUT_SIZE: [17, 129, 129]
  OUTPUT_SIZE: [17, 129, 129]
  NORM_MODE: gn
  MIXED_PRECESION: False
  FILTERS: [32, 64, 96, 128, 160]
  RETURN_FEATS: [0, 4] # for feature alignment
DATASET:
  INPUT_PATH: datasets/CySGAN/train/ # or your own dataset path
  IMAGE_NAME: imageX.tif
  LABEL_NAME: labelX_smooth_dilate.tif
  PAD_SIZE: [4, 42, 42]
  MATCH_ACT: tanh
  REJECT_SAMPLING:
    SIZE_THRES: 1000
    P: 0.9
  DISTRIBUTED: True
# Configurations specific to GANLossSSL
UNLABELED:
  IMAGE_NAME: imageY.tif
  GAN_UNLABELED_ONLY: False
  D_DILATION: 2 # dilated conv in the discriminator
  SAMPLES_PER_BATCH: 2
  FEATURE_ALIGNMENT: 
    ENABLED: True # enable feature alignment
    D_IS_ISOTROPIC: [True, False]
    D_FILTERS: [[64, 64, 64, 64, 64], [64, 64, 64, 128, 128]]
    STRIDE_LIST: [[1, 1, 1, 1, 1], "default"]
SOLVER:
  NAME: AdamW
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 2e-3
  ITERATION_STEP: 1
  ITERATION_SAVE: 5000
  ITERATION_TOTAL: 100000
  SAMPLES_PER_BATCH: 2
MONITOR:
  ITERATION_NUM: [20, 200]
INFERENCE:
  MODEL_RETURN_FEATS: None # features not needed for inference
  INPUT_SIZE: [33, 257, 257]
  OUTPUT_SIZE: [33, 257, 257]
  IMAGE_NAME: imageY.tif
  OUTPUT_NAME: pred0.h5
  PAD_SIZE: [4, 16, 16]
  AUG_MODE: mean
  AUG_NUM: None
  STRIDE: [16, 128, 128]
  SAMPLES_PER_BATCH: 4
