MODEL:
  IN_PLANES: 1
  OUT_PLANES: 3
  TARGET_OPT: ['0','4-1-1', '5-3d-1-0-2.0']
  LOSS_OPTION:
  - - WeightedBCEWithLogitsLoss
    - DiceLoss
  - - WeightedBCEWithLogitsLoss
    - DiceLoss
  - - WeightedMSE
  LOSS_WEIGHT: [[1.0, 0.5], [1.0, 0.5], [5.0]]
  WEIGHT_OPT: [['1', '0'], ['1', '0'], ['0']]
  OUTPUT_ACT: [['none', 'sigmoid'], ['none', 'sigmoid'], ['tanh']]
INFERENCE:
  OUTPUT_ACT: ['sigmoid', 'sigmoid', 'tanh']
  OUTPUT_PATH: outputs/NucExM_DA_BCD/test/
  MODEL_RETURN_FEATS: None # features not needed for inference
DATASET:
  OUTPUT_PATH: outputs/NucExM_DA_BCD/
