MODEL:
  ARCHITECTURE: swinunetr
  INPUT_SIZE: [64, 128, 128]  # Must be 2^n
  OUTPUT_SIZE: [64, 128, 128]
  DEPTHS: (2, 2, 2, 2)
  SWIN_UNETR_NUM_HEADS: (3, 6, 12, 24)
  SWIN_UNETR_FEATURE_SIZE: 48
  NORM_NAME: 'instance'
  ISOTROPY: (False, True, True, True)
  SWIN_UNETR_DROPOUT_RATE: 0.0
  ATTN_DROP_RATE: 0.0
  DROPOUT_PATH_RATE:  0.0
  NORMALIZE: True
  USE_CHECKPOINT: False
  SPATIAL_DIMS: 3
  DOWNSAMPLE: 'merging'
  USE_V2: False
DATASET:
  OUTPUT_PATH: outputs/SNEMI_SwinUNETR
SOLVER:
  NAME: AdamW
  BASE_LR: 0.001
INFERENCE:
  INPUT_SIZE: [32, 256, 256]
  OUTPUT_SIZE: [32, 256, 256]
  OUTPUT_PATH: outputs/SNEMI_SwinUNETR/test
  OUTPUT_NAME: result_swinunetr.h5
  STRIDE: [16, 128, 128]
  SAMPLES_PER_BATCH: 2
