# All other configurations are set by default. If you want to add new config options,
# please modify ../connectomics/config/defaults.py
SYSTEM:
  NUM_GPUS: 2
  NUM_CPUS: 16
AUGMENTOR:
  SMOOTH: False
MODEL:
  INPUT_SIZE: [17, 257, 257]
  OUTPUT_SIZE: [17, 257, 257]
  IN_PLANES: 1
  OUT_PLANES: 3
  TARGET_OPT: ["2"]
  LABEL_EROSION: 1
  LOSS_OPTION: [["WeightedBCEWithLogitsLoss", "DiceLoss"]]
  LOSS_WEIGHT: [[1.0, 0.5]]
  WEIGHT_OPT: [["1", "0"]]
  OUTPUT_ACT: [["none", "sigmoid"]]
  FILTERS: [32, 64, 96, 128, 160]
  NORM_MODE: gn
DATASET:
  IMAGE_NAME: train_image.h5
  LABEL_NAME: train_label.h5
  INPUT_PATH: datasets/SNEMI3D/ # or your own dataset path
  OUTPUT_PATH: outputs/SNEMI3D/
  PAD_SIZE: [4, 64, 64]
SOLVER:
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.02
  ITERATION_STEP: 1
  ITERATION_SAVE: 10000
  ITERATION_TOTAL: 150000
  SAMPLES_PER_BATCH: 2
MONITOR:
  ITERATION_NUM: [200, 1000]
INFERENCE:
  INPUT_SIZE: [17, 513, 513]
  OUTPUT_SIZE: [17, 513, 513]
  OUTPUT_ACT: ["sigmoid"]
  IMAGE_NAME: test-input.tif # or path to your test images
  OUTPUT_PATH: outputs/SNEMI3D/test
  OUTPUT_NAME: result.h5
  PAD_SIZE: [4, 32, 32]
  AUG_MODE: min
  AUG_NUM: None
  STRIDE: [8, 256, 256]
  SAMPLES_PER_BATCH: 4
