SYSTEM:
  NUM_GPUS: 2
  NUM_CPUS: 8
MODEL:
  INPUT_SIZE: [1, 128, 128]
  OUTPUT_SIZE: [1, 128, 128]
  IN_PLANES: 1
  ACT_MODE: silu
  NORM_MODE: gn
TWOSTREAM:
  HIDDEN_DIMS: [64, 128, 128, 256, 256, 512]
  WIDTH: 128
DATASET:
  INPUT_PATH: datasets/JWR15/roi_8x8x3um/
  OUTPUT_PATH: outputs/JWR15_Synapse/
  PAD_SIZE: [0, 0, 0]
  DISTRIBUTED: True
  DO_2D: True
SOLVER:
  NAME: AdamW
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 1e-3
  ITERATION_STEP: 1
  ITERATION_SAVE: 20000
  ITERATION_TOTAL: 400000
  SAMPLES_PER_BATCH: 256
  WEIGHT_DECAY: 0.0
MONITOR:
  ITERATION_NUM: [100, 1000]
