SYSTEM:
  NUM_GPUS: 2
  NUM_CPUS: 16
MODEL:
  ARCHITECTURE: unet_plus_3d
  BLOCK_TYPE: residual_se
  INPUT_SIZE: [9, 257, 257]
  OUTPUT_SIZE: [9, 257, 257]
  FILTERS: [32, 64, 96, 128, 160]
  IN_PLANES: 1
  NORM_MODE: gn
DATASET:
  INPUT_PATH: datasets/SingleCell/EM
  IMAGE_NAME: raw_data15.tif
  PAD_SIZE: [2, 0, 0]
  DATA_SCALE: [1.0, 0.5, 0.5]
  REJECT_SAMPLING:
    SIZE_THRES: 2000
    P: 0.9
  DISTRIBUTED: False
AUGMENTOR:
  SMOOTH: False
SOLVER:
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.04
  ITERATION_STEP: 1
  ITERATION_SAVE: 5000
  ITERATION_TOTAL: 100000
  SAMPLES_PER_BATCH: 2
MONITOR:
  ITERATION_NUM: [40, 400]
INFERENCE:
  INPUT_SIZE: [9, 257, 257]
  OUTPUT_SIZE: [9, 257, 257]
  IMAGE_NAME: test_image.h5
  OUTPUT_NAME: result.h5
  PAD_SIZE: [2, 0, 0]
  AUG_NUM: None
  STRIDE: [4, 128, 128]
  SAMPLES_PER_BATCH: 4
  OUTPUT_SCALE: [1.0, 1.0, 1.0]
