MODEL:
  OUT_PLANES: 5
  TARGET_OPT: ["9-5"]
  LOSS_OPTION: [["WeightedCE"]]
  LOSS_KWARGS_KEY: [[["class_weight"]]]
  LOSS_KWARGS_VAL: [[[[1.0, 2.0, 3.0, 4.0, 5.0]]]] # weights for semantic classes
  LOSS_WEIGHT: [[1.0]]
  WEIGHT_OPT: [["0"]]
  OUTPUT_ACT: [["none"]]
DATASET:
  LABEL_NAME: lab_foreground15_reduced.tif
  OUTPUT_PATH: outputs/SingleCell-UNet3D-Semantic/
INFERENCE:
  OUTPUT_ACT: ["sigmoid", "softmax"]
  OUTPUT_PATH: outputs/SingleCell-UNet3D-Semantic/test/
