SYSTEM:
  NUM_GPUS: 1
  NUM_CPUS: 4
MODEL:
  ARCHITECTURE: unet_2d
  BLOCK_TYPE: residual_se
  INPUT_SIZE: [1, 193, 193]
  OUTPUT_SIZE: [1, 193, 193]
  IN_PLANES: 1
  OUT_PLANES: 2
  TARGET_OPT: ["2"]
  LOSS_OPTION:
    - - WeightedBCEWithLogitsLoss
      - DiceLoss
  LOSS_WEIGHT: [[1.0, 0.5]]
  WEIGHT_OPT: [["1", "0"]]
  OUTPUT_ACT: [["none", "sigmoid"]]
  NORM_MODE: bn
  MIXED_PRECESION: False
  FILTERS: [32, 64, 128, 256, 512]
DATASET:
  INPUT_PATH: datasets/Hydra/seg_2d/
  IMAGE_NAME: hydra_w03_export_s024.png
  LABEL_NAME: hydra_w03_export_s024_seg.png
  OUTPUT_PATH: outputs/Hydra_UNet_2D/
  PAD_SIZE: [0, 32, 32]
  REJECT_SAMPLING:
    SIZE_THRES: 1000
    DIVERSITY: 2
    P: 1.0
  DO_2D: True
  LOAD_2D: True
  DATA_SCALE: [1.0, 0.25, 0.25]
AUGMENTOR:
  MISSINGPARTS:
    ENABLED: False
SOLVER:
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.01
  ITERATION_STEP: 1
  ITERATION_SAVE: 5000
  ITERATION_TOTAL: 100000
  SAMPLES_PER_BATCH: 8
INFERENCE:
  INPUT_SIZE: [1, 513, 513]
  OUTPUT_SIZE: [1, 513, 513]
  DATA_SCALE: [1.0, 1.0, 1.0]
  OUTPUT_ACT: ["sigmoid"]
  INPUT_PATH: datasets/Hydra
  IMAGE_NAME: slice_0025/**/*.png
  DO_SINGLY: True
  OUTPUT_PATH: outputs/Hydra_UNet_2D/test_mip2/
  OUTPUT_NAME: pred
  PAD_SIZE: [0, 64, 64]
  AUG_NUM: 4
  AUG_MODE: min
  STRIDE: [1, 256, 256]
  SAMPLES_PER_BATCH: 16
