SYSTEM:
  NUM_GPUS: 2
  NUM_CPUS: 16
MODEL:
  ARCHITECTURE: deeplabv3c
  BACKBONE: resnet101
  AUX_OUT: True
  INPUT_SIZE: [1, 513, 513]
  OUTPUT_SIZE: [1, 513, 513]
  IN_PLANES: 1
  OUT_PLANES: 1
  TARGET_OPT: ["0-1"]
  LOSS_OPTION:
    - - WeightedBCEWithLogitsLoss
      - DiceLoss
  LOSS_WEIGHT: [[1.0, 0.5]]
  WEIGHT_OPT: [["1", "0"]]
  OUTPUT_ACT: [["none", "sigmoid"]]
  NORM_MODE: gn
  MIXED_PRECESION: False
AUGMENTOR:
  SMOOTH: False
DATASET:
  INPUT_PATH: datasets/amyloid_plaque/
  IMAGE_NAME: image/*.png
  LABEL_NAME: label/*.png
  OUTPUT_PATH: outputs/Amyloid_Plaque_Deeplab/
  PAD_SIZE: [0, 64, 64]
  REJECT_SAMPLING:
    SIZE_THRES: 1000
    P: 1.0
  DISTRIBUTED: True
  DO_2D: True
  LOAD_2D: True
  DATA_SCALE: [1.0, 0.5, 0.5]
SOLVER:
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.04
  ITERATION_STEP: 1
  ITERATION_SAVE: 5000
  ITERATION_TOTAL: 100000
  SAMPLES_PER_BATCH: 4
MONITOR:
  ITERATION_NUM: [40, 400]
INFERENCE:
  INPUT_SIZE: [1, 2049, 2049]
  OUTPUT_SIZE: [1, 2049, 2049]
  OUTPUT_ACT: ["sigmoid"]
  IMAGE_NAME: datasets/amyloid_plaque/test_path.txt
  IS_ABSOLUTE_PATH: True
  DO_SINGLY: True
  OUTPUT_PATH: outputs/Amyloid_Plaque_Deeplab/test/
  OUTPUT_NAME: pred
  PAD_SIZE: [0, 64, 64]
  AUG_NUM: 8
  AUG_MODE: mean
  STRIDE: [1, 1024, 1024]
  SAMPLES_PER_BATCH: 2
